apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T11:24:Z"  
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "5984"  
  uid: a3a1e156-cf78-47e0-9352-8e9eaba5b0ed  
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.106.116.166  
  clusterIPs:
  - 10.106.116.166 
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31302  
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}